


spring:
  application:
    name: consumer
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/tp_music?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        127.0.0.1:8848

server:
  port: 8764
mybatis:
  type-aliases-package: com.istudy.collection.pojo
  mapper-locations: classpath:mapper/*.xml
