spring:
  application:
    name: singer
  cloud:
    nacos:
      discovery:
        127.0.0.1:8848
  datasource:
    url: jdbc:mysql://localhost:3306/tp_music?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.istudy.singer.pojo
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8763
