server:
  port: 8762
spring:
  application:
    name: comment
  datasource:
    url: jdbc:mysql://localhost:3306/tp_music?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
       discovery:
         127.0.0.1:8848
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.istudy.comment.pojo


